name: kkpp24
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - ipywidgets
  - jupyterlab
  - nbconvert
  - numpy=2.0
  - pandas=2.2
  - scipy=1.15
  - matplotlib=3.10
  - seaborn=0.13
  - arviz=0.21
  - pymc=5.22
  - numba=0.60
  - openpyxl=3.1
  - geopandas=1.0
  - plotly=6.0
  - pointpats=2.5
  - rasterio=1.4
  - scikit-image=0.25
  - imagecodecs<2026
  - statsmodels=0.14
  - xarray>=2025.1,<2026.0
  - pip:
      - chronocluster @ git+https://github.com/wccarleton/chronocluster.git
